version: '3'
services:
    proxy:
        image: "nginx:1-alpine"
        volumes:
            - ./config/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "8080:80"
        links:
            - frontend
            - backend
            - unicorn
        command: /bin/sh -c "envsubst < /etc/nginx/nginx.conf > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"

    frontend:
        image: "bptlab/argos-frontend:beta"
        env_file:
            - host.env
        volumes:
            - ./config/frontend-config.js:/src/config/config.js

    backend:
        image: "bptlab/argos-backend:beta"
        env_file:
            - database.env
            - host.env
        volumes:
            - ./config/argos-backend.properties:/src/main/resources/argos-backend.properties
        links:
            - database
        depends_on:
            - unicorn

    unicorn:
        image: "bptlab/unicorn:latest"
        env_file:
            - database.env
        volumes:
            - ./config/unicorn.properties:/usr/local/tomcat/conf/unicorn.properties
        links:
            - database

    database:
        image: "mysql:5"
        env_file:
            - database.env